/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "index.html",
    "./Pages/*.{html,js}",
  ],
  theme: {
    extend: {
      colors:{
        brandRed: "#E35053",
        brandGrey: "#212529",
        brandGreen: "#E0F7EF",
        brandGreen1: "#358F80",
        brandWhite: "#FFFFFF",
        brandBlue: "#0096C7",
        brandBlue2: "#0077B6",
        brandBlue6: "#CAF0F8",
        brandBrown: "#7F5539",
        brandWhite2: "#F2F2F2",
        brandWhite5: "#F7F7F7",
        brandBlack1: "#343A40",
        brandBlack2: "#495057",
        brandBlack3: "#6C757D",
        brandBlack4: "#ADB5BD",
        brandBlack5: "#CED4DA",
        brandBlack6: "#DEE2E6",
        brandBlack1x: "#444443",
        brandPurple: "#775BE9",
        brandOrange: "#ED6536",
      },
      borderRadius:{
        five: "0.3125rem",
        ten: "0.625rem",
        twenty: "1.25rem",
        thirty: "1.875rem",
        forty: "2.5rem",
        fifty: "3.125rem",
        fiftyPercent: "50%",
      },
      content:{
        "logo": "url['./assets/images/logo.svg']",
      },
      screens:{
        'mds': {'min': '500px', 'max': '639px'},
        'xs': {'min': '200px', 'max': '300px'},
        'xsHeight': { 'raw': '(max-height:510px)' },
      },
      spacing:{
        '18': '4.5rem',
        navIcon: '20px',
        authWrapper: '34%',
      },
      fontSize: {
        sm: ['14px', '20px'],
        thirteen: ['13px', '18px'],
        fifteen: ['15px', '20px'],
      },
      fontFamily:{
        biotifBlack: ["biotif-black", "sans-serif"],
        biotifBlackItalic: ["biotif-black-italic", "sans-serif"],
        biotifBold: ["biotif-bold", "sans-serif"],
        biotifBold2: ["biotif-bold-2", "sans-serif"],
        biotifBoldItalic: ["biotif-bold-italic", "sans-serif"],
        biotifBook: ["biotif-book", "sans-serif"],
        biotifBook2: ["biotif-book-2", "sans-serif"],
        biotifBookItalic: ["biotif-book-italic", "sans-serif"],
        biotifExtraBold: ["biotif-extra-bold", "sans-serif"],
        biotifExtraBoldItalic: ["biotif-extra-bold-italic", "sans-serif"],
        biotifLight: ["biotif-light", "sans-serif"],
        biotifLight2: ["biotif-light-2", "sans-serif"],
        biotifLightItalic: ["biotif-light-italic", "sans-serif"],
        biotifMedium: ["biotif-medium", "sans-serif"],
        biotifMediumItalic: ["biotif-medium-italic", "sans-serif"],
        biotifRegular: ["biotif-regular", "sans-serif"],
        biotifRegular2: ["biotif-regular-2", "sans-serif"],
        biotifRegularItalic: ["biotif-regular-italic", "sans-serif"],
        biotifSemiBold: ["biotif-semi-bold", "sans-serif"],
        biotifSemiBold2: ["biotif-semi-bold-2", "sans-serif"],
        biotifSemiBoldItalic: ["biotif-semi-bold-italic", "sans-serif"],
      },
      zIndex: {
        '70': '70',
        '80': '80',
        '100': '100',
      },
      borderWidth:{
        '0.3': '0.01875rem',
        '0.5': '0.03125rem',
      },
      minWidth: {
        '1/2': '50%',
        '350': '21.875rem',
      },
      spacing:{
        '3px': '0.1875rem',
        'sixPixel': "0.375rem",
        '18': '4.5rem',
        'top18.5': '74px',
        '18px': '1.125rem',
        '40px': '2.5rem',
        '45px': '2.8125rem',
        '60px': '3.75rem',
        '88': '5.5rem',
        '100': '6.25rem',
        '130px': '8.125rem',
        '202': '12.625rem',
        '254': '15.875rem',
        '280': '17.5rem',
        '307': '19.1875rem',
        '322': '20.125rem',
        '350': '21.875rem',
        '380': '23.75rem',
        '400': '25rem',
        '410': '25.625rem',
        '420': '26.25rem',
        '550': '34.375rem',
        '618': '38.625rem',
        '700': '43.75rem',
        '70px': '4.375rem',
        navIcon: '20px',
        authWrapper: '34%',
        dashScrollableHeight: 'calc(100% - 10px)',
        icon: '20px',
        onePixel: '0.0625rem',
        threePixel: '0.150rem',
        tenPixel: '0.625rem',
        fivePercent: '5%',
        tenPercent: '10%',
        twelvePercent: '12%',
        thirteenPercent: '13%',
        fourteenPercent: '14%',
        fifteenPercent: '15%',
        seventeenPercent: '17%',
        eighteenPercent: '18%',
        nineteenPercent: '19%',
        twentyPercent: '20%',
        twentyTwoPercent: '22%',
        twentyFourPercent: '24%',
        twentyFivePercent: '25%',
        thirtyPercent: '30%',
        thirtyTwoPercent: '32%',
        thirtyFivePercent: '35%',
        thirtySixPercent: '36%',
        thirtyEightPercent: '38%',
        fortyPercent: '40%',
        fortyFivePercent: '45%',
        fortySevenPercent: '47%',
        fortyEightPercent: '48%',
        fiftyPercent: '50%',
        fiftyTwoPercent: '52%',
        fiftyFivePercent: '55%',
        sixtyPercent: '60%',
        sixtyTwoPercent: '62%',
        sixtyFivePercent: '65%',
        sixtySixPercent: '66%',
        sixtySevenPercent: '67%',
        seventyPercent: '70%',
        seventyFivePercent: '75%',
        seventyEightPercent: '78%',
        eightyPercent: '80%',
        eightyOnePercent: '81%',
        eightyThreePercent: '83%',
        eightyFourPercent: '84%',
        eightyFivePercent: '85%',
        eightyEightPercent: '88%',
        ninetyPercent: '90%',
        ninetyFivePercent: '95%',
        hundredPercent: '100%',
        oneTwentyPercent: '120%',
        oneFiftyPercent: '150%',
      },
    },
  },
  plugins: [],
}
